import Head from 'next/head'
import Image from 'next/image'
import styled from 'styled-components'
import Navbar from '../../components/Navbar'
import Footer from '../../components/Footer'
import DesignTitle from '../../components/DesignTitle'
import DesignCards from '../../components/DesignCards'
import DesignType from '../../components/DesignType'
import CallToAction from '../../components/CallToAction'

const Container = styled.main`
  min-height: 100vh;
  padding: 20px 70px;
`

const DesignTypes = styled.div`
  display: grid;
  grid-template-columns: 1fr 1fr;
  gap: 20px;
  height: 300px;
  margin-bottom: 90px;
`

export default function Home() {

  const WEB_DESIGNS = [
    {
      title: 'Express',
      description: 'A multi-carrier shipping website for ecommerce businesses'
    },
    {
      title: 'Transfer',
      description: 'Site for low-cost money transfers and sending money within seconds'
    },
    {
      title: 'Photon',
      description: 'A state-of-the-art music player with high-resolution audio and DSP effects'
    },
    {
      title: 'Builder',
      description: 'Connects users with local contractors based on their location'
    },
    {
      title: 'Blogr',
      description: 'Blogr is a platform for creating an online blog or publication'
    },
    {
      title: 'Camp',
      description: 'Get expert training in coding, data, design, and digital marketing'
    },
  ]

  return (
    <div>
      <Head>
        <title>Designo - Web Design</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
    
      <Container>
        <Navbar />
        <DesignTitle />
        <DesignCards designs={WEB_DESIGNS} />
        
        <DesignTypes>
          <DesignType type="APP DESIGN" />
          <DesignType type="GRAPHIC DESIGN" />
        </DesignTypes>

        <CallToAction />
      </Container>

      <Footer />
    </div>
  )
}
