import Head from 'next/head'
import Image from 'next/image'
import styled from 'styled-components'
import Navbar from '../../components/Navbar'
import Footer from '../../components/Footer'
import DesignTitle from '../../components/DesignTitle'
import DesignCards from '../../components/DesignCards'
import DesignType from '../../components/DesignType'
import CallToAction from '../../components/CallToAction'
import { devices } from '../../styles/media_queries'

const Container = styled.main`
  min-height: 100vh;
  padding: 20px 70px;

  @media ${devices.tablet} {
    padding: 20px 40px;
  };

  @media ${devices.mobile} {
    padding: 20px;
  };
`

const DesignTypes = styled.div`
  display: grid;
  grid-template-columns: 1fr 1fr;
  gap: 20px;
  height: 300px;
  margin-bottom: 90px;

  @media ${devices.tablet} {
    display: flex;
    flex-direction: column;
  };
`

export default function Home() {

  const WEB_DESIGNS = [
    {
      title: 'Express',
      description: 'A multi-carrier shipping website for ecommerce businesses',
      imageFilename: 'image-express'
    },
    {
      title: 'Transfer',
      description: 'Site for low-cost money transfers and sending money within seconds',imageFilename: 'image-express',
      imageFilename: 'image-transfer'
    },
    {
      title: 'Photon',
      description: 'A state-of-the-art music player with high-resolution audio and DSP effects',
      imageFilename: 'image-photon'
    },
    {
      title: 'Builder',
      description: 'Connects users with local contractors based on their location',
      imageFilename: 'image-builder'
    },
    {
      title: 'Blogr',
      description: 'Blogr is a platform for creating an online blog or publication',
      imageFilename: 'image-blogr'
    },
    {
      title: 'Camp',
      description: 'Get expert training in coding, data, design, and digital marketing',
      imageFilename: 'image-camp'
    },
  ]

  return (
    <div>
      <Head>
        <title>Designo - Web Design</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="initial-scale=1.0, width=device-width"></meta>
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Navbar />
      <DesignTitle />
    
      <Container>
        <DesignCards designType="web-design" designs={WEB_DESIGNS} />
        
        <DesignTypes>
          <DesignType type="APP DESIGN" />
          <DesignType type="GRAPHIC DESIGN" />
        </DesignTypes>
      </Container>

      <CallToAction />
      <Footer />
    </div>
  )
}
