import Head from 'next/head'
import Image from 'next/image'
import styled from 'styled-components'
import Navbar from '../../components/Navbar'
import Footer from '../../components/Footer'
import DesignTitle from '../../components/DesignTitle'
import DesignCards from '../../components/DesignCards'
import DesignType from '../../components/DesignType'
import CallToAction from '../../components/CallToAction'

const Container = styled.main`
  min-height: 100vh;
  padding: 20px 70px;
`

const DesignTypes = styled.div`
  display: grid;
  grid-template-columns: 1fr 1fr;
  gap: 20px;
  height: 300px;
  margin-bottom: 90px;
`

export default function GraphicDesign() {

  const GRAPHIC_DESIGNS = [
    {
      title: 'TIM BROWN',
      description: 'A book cover designed for Tim Brown’s new release, ‘Change’',
      imageFilename: 'image-change'
    },
    {
      title: 'BOXED WATER',
      description: 'A simple packaging concept made for Boxed Water',
      imageFilename: 'image-boxed-water'
    },
    {
      title: 'SCIENCE!',
      description: 'A poster made in collaboration with the Federal Art Project',
      imageFilename: 'image-science'
    },
  ]

  return (
    <div>
      <Head>
        <title>Designo - Graphic Design</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
    
      <Container>
        <Navbar />
        <DesignTitle type="graphic-design"/>
        <DesignCards designType="graphic-design" designs={GRAPHIC_DESIGNS} />
        
        <DesignTypes>
          <DesignType type="WEB DESIGN" />
          <DesignType type="APP DESIGN" />
        </DesignTypes>

        <CallToAction />
      </Container>

      <Footer />
    </div>
  )
}
