import Head from 'next/head'
import Image from 'next/image'
import styled from 'styled-components'
import Navbar from '../components/Navbar'

const Container = styled.main`
  min-height: 100vh;
  padding: 20px 30px;
`

export default function Home() {
  return (
    <div>
      <Head>
        <title>Designo</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
    
      <Container>
        <Navbar />
      </Container>
    </div>
  )
}
