import Head from 'next/head'
import Image from 'next/image'
import styled from 'styled-components'
import Navbar from '../components/Navbar'
import DesignTypes from '../components/DesignTypes'
import HomeTopInfo from '../components/HomeTopInfo'
import Adjectives from '../components/Adjectives'
import CallToAction from '../components/CallToAction'
import Footer from '../components/Footer'
import { devices } from '../styles/media_queries'

const Container = styled.main`
  min-height: 100vh;
  padding: 20px 70px;

  @media ${devices.tablet} {
    padding: 20px 40px;
  };
`

export default function Home() {
  return (
    <div>
      <Head>
        <title>Designo</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
    
      <Container>
        <Navbar />
        <HomeTopInfo />
        <DesignTypes />
        <Adjectives />
        <CallToAction />
      </Container>

      <Footer />
    </div>
  )
}
