import Head from 'next/head'
import Image from 'next/image'
import styled from 'styled-components'
import Navbar from '../components/Navbar'
import DesignTypes from '../components/DesignTypes'
import HomeTopInfo from '../components/HomeTopInfo'
import Adjectives from '../components/Adjectives'
import CallToAction from '../components/CallToAction'
import Footer from '../components/Footer'
import { devices } from '../styles/media_queries'

const Container = styled.main`
  min-height: 100vh;
  padding: 20px 70px;
  width: 100%;

  @media ${devices.tablet} {
    padding: 20px 40px;
  };

  @media ${devices.mobile} {
    padding: 25px;
  };
`

const MarginOffset = styled.div`
  height: 65px;
  width: 100%;
`

export default function Home() {
  return (
    <div>
      <Head>
        <title>Designo</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="initial-scale=1.0, width=device-width"></meta>
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Navbar />
      <HomeTopInfo />
    
      <Container>
        <DesignTypes />
        <Adjectives />
      </Container>

      <CallToAction />
      <Footer />
    </div>
  )
}
