import Head from 'next/head'
import Image from 'next/image'
import styled from 'styled-components'
import Navbar from '../../components/Navbar'
import Footer from '../../components/Footer'
import DesignTitle from '../../components/DesignTitle'
import DesignCards from '../../components/DesignCards'
import DesignType from '../../components/DesignType'
import CallToAction from '../../components/CallToAction'
import { devices } from '../../styles/media_queries'

const Container = styled.main`
  min-height: 100vh;
  padding: 20px 70px;

  @media ${devices.tablet} {
    padding: 20px 40px;
  };

  @media ${devices.mobile} {
    padding: 20px;
  };
`

const DesignTypes = styled.div`
  display: grid;
  grid-template-columns: 1fr 1fr;
  gap: 20px;
  height: 300px;
  margin-bottom: 90px;

  @media ${devices.tablet} {
    display: flex;
    flex-direction: column;
  };
`

export default function AppDesign() {

  const APP_DESIGNS = [
    {
      title: 'AIRFILTER',
      description: 'Solving the problem of poor indoor air quality by filtering the air',
      imageFilename: 'image-airfilter'
    },
    {
      title: 'EYECAM',
      description: 'Product that lets you edit your favorite photos and videos at any time',
      imageFilename: 'image-eyecam'
    },
    {
      title: 'FACEIT',
      description: 'Get to meet your favorite internet superstar with the faceit app',
      imageFilename: 'image-faceit'
    },
    {
      title: 'TODO',
      description: 'A todo app that features cloud sync with light and dark mode',
      imageFilename: 'image-todo'
    },
    {
      title: 'LOOPSTUDIOS',
      description: 'A VR experience app made for Loopstudios',
      imageFilename: 'image-loopstudios'
    },
  ]

  return (
    <div>
      <Head>
        <title>Designo - App Design</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="initial-scale=1.0, width=device-width"></meta>
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Navbar />
      <DesignTitle type="app-design"/>
    
      <Container>
        <DesignCards designType="app-design" designs={APP_DESIGNS} />
        
        <DesignTypes>
          <DesignType type="WEB DESIGN" />
          <DesignType type="GRAPHIC DESIGN" />
        </DesignTypes>
      </Container>

      <CallToAction />

      <Footer />
    </div>
  )
}
